services:
    postgres:
        image: postgres:16.2
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        healthcheck:
            test: pg_isready -d ${DB_NAME}
            interval: 5s
            timeout: 5s
            retries: 30
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - TZ=Europe/Moscow
        ports:
            - '${DB_PORT_EXTERNAL}:5432'
        volumes:
            - postgres:/var/lib/postgresql/data:delegated
            - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf

    php:
        build:
            context: docker/php
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        depends_on:
            postgres:
                condition: service_healthy
        working_dir: /var/www/html
        tty: true
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            COMPOSER_ROOT_VERSION: ${COMPOSER_ROOT_VERSION}
        volumes:
            - .:/var/www/html:cached
            - ~/.composer:/var/www/.composer
        command: sh -c "rr serve -d -c ./docker/php/.rr.yaml"
        labels:
            - traefik.enable=true
            - traefik.http.routers.php.service=php
            - traefik.http.routers.php.entryPoints=https
            - traefik.http.routers.php.rule=Host(`api.symfony-template.localhost`)
            - traefik.http.routers.php.tls=true
            - traefik.http.services.php.loadBalancer.server.port=80

    traefik:
        image: traefik:v3.0
        command:
            - --api.insecure=true
            - --providers.file.filename=/config/config.toml
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --entrypoints.http.address=:80
            - --entrypoints.http.http.redirections.entrypoint.to=https
            - --entrypoints.http.http.redirections.entrypoint.scheme=https
            - --entrypoints.https.address=:443
        ports:
            - '443:443'
            - '8080:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./docker/traefik:/config
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.entryPoints=https
            - traefik.http.routers.traefik.rule=Host(`traefik.symfony-template.localhost`)
            - traefik.http.routers.traefik.tls=true
            - traefik.http.services.traefik.loadBalancer.server.port=8080

volumes:
    postgres: null
